// =============================================================================
//  AH-RISCV : synchronous data memory (64 KB BRAM). (c) 2026 Ali Hussein. GPL-3.0.
//  Hardware signature: "AHUSSEIN".  Generated by tools/ah_mkdmem.py.
//
//  Read and write are driven from the EX stage (address = ALU result), so the
//  registered read data is valid in the MEM stage -- load timing, forwarding,
//  and the load-use stall are identical to the old combinational memory.
//  Initialised .data/.rodata are baked into the array below; the rest is zero
//  (so .bss starts cleared and the stack/heap have room).
// =============================================================================
module ah_dmem (
    input         clk,
    input  [63:0] addr,      // EX-stage address (ALU result)
    input  [63:0] wdata,     // store data (raw rs2)
    input  [2:0]  funct3,
    input         mem_read,
    input         mem_write,
    output reg [63:0] rdata  // valid next cycle (MEM stage), sign/zero-extended
);
    reg [63:0] mem [0:8191];
    integer i;
    initial begin
        for (i=0;i<8192;i=i+1) mem[i]=64'd0;
        mem[0]=64'h5349522d48410a0d;
        mem[1]=64'h5265657246205643;
        mem[2]=64'h0a0d707520534f54;
        mem[4]=64'h0000000000000041;
        mem[5]=64'h0000000000000042;
        mem[6]=64'h00000000454c4449;
        mem[7]=64'h000018c4000018d0;
        mem[8]=64'h0000198800001974;
        mem[9]=64'h00001a3c00001980;
        mem[10]=64'h00001a5400001a30;
        mem[11]=64'h00001a6000001a68;
        mem[12]=64'h0000000000000004;
        mem[13]=64'h0000000010000048;
        mem[14]=64'h00000000000061a8;
        mem[15]=64'h0000000040000eb0;
        mem[16]=64'h0000000040000088;
        mem[17]=64'h00000000aaaaaaaa;
        mem[18]=64'h0000000040005f48;
    end
    wire [12:0] widx = addr[15:3];
    wire [5:0]  boff = {addr[2:0],3'b000};
    // byte/half/word/double store (assumes natural alignment)
    always @(posedge clk) if (mem_write) begin
        case (funct3[1:0])
            2'b00: mem[widx][boff +:  8] <= wdata[7:0];
            2'b01: mem[widx][boff +: 16] <= wdata[15:0];
            2'b10: mem[widx][boff +: 32] <= wdata[31:0];
            2'b11: mem[widx]             <= wdata;
        endcase
    end
    // synchronous read: latch the word + alignment, extend combinationally
    reg [63:0] word_r; reg [5:0] boff_r; reg [2:0] f3_r;
    always @(posedge clk) begin
        word_r <= mem[widx]; boff_r <= boff; f3_r <= funct3;
    end
    wire [63:0] sub = word_r >> boff_r;
    always @(*) begin
        case (f3_r)
            3'b000: rdata = {{56{sub[7]}},  sub[7:0]};
            3'b001: rdata = {{48{sub[15]}}, sub[15:0]};
            3'b010: rdata = {{32{sub[31]}}, sub[31:0]};
            3'b011: rdata = word_r;
            3'b100: rdata = {56'b0, sub[7:0]};
            3'b101: rdata = {48'b0, sub[15:0]};
            3'b110: rdata = {32'b0, sub[31:0]};
            default: rdata = word_r;
        endcase
    end
endmodule
