// ============================================================================
//  AH-RISCV : unified dual-port physical RAM. (c) 2026 Ali Hussein. GPL-3.0.
//  Port A = instruction fetch (read 32-bit). Port B = data (r/w, sized).
//  Both index one array, so code and data share one physical address space
//  (RAM base 0x8000_0000). Generated by tools/ah_mkmem.py.
// ============================================================================
module ah_mem (
    input         clk,
    input  [63:0] a_addr,  output reg [31:0] a_rdata,         // fetch port
    input  [63:0] b_addr,  input [63:0] b_wdata, input [2:0] b_funct3,
    input         b_re,    input b_we,  output reg [63:0] b_rdata  // data port
);
    localparam WORDS=32768;
    reg [63:0] mem [0:WORDS-1];
    integer i;
    initial begin
        for (i=0;i<WORDS;i=i+1) mem[i]=64'd0;
        mem[0]=64'h0011011b00002137;
        mem[1]=64'h154000ef01211113;
        mem[2]=64'h100007370000006f;
        mem[3]=64'h0007478300870713;
        mem[4]=64'hfe078ce30017f793;
        mem[5]=64'h00a78023100007b7;
        mem[6]=64'hff01011300008067;
        mem[7]=64'h0081302300113423;
        mem[8]=64'h0005450300050413;
        mem[9]=64'h0014041300050a63;
        mem[10]=64'h00044503fc5ff0ef;
        mem[11]=64'h00813083fe051ae3;
        mem[12]=64'h0101011300013403;
        mem[13]=64'hfc01011300008067;
        mem[14]=64'h0291342302113c23;
        mem[15]=64'h0004879300810493;
        mem[16]=64'h0090059300a00693;
        mem[17]=64'h02d5773306050e63;
        mem[18]=64'h00e780230307071b;
        mem[19]=64'h02d5553300050613;
        mem[20]=64'h0017879300078713;
        mem[21]=64'h4097073bfec5e2e3;
        mem[22]=64'h0007079b0017071b;
        mem[23]=64'h0281382302078e63;
        mem[24]=64'h00f6843300810693;
        mem[25]=64'h00f484b3fff48493;
        mem[26]=64'h02071713fff7071b;
        mem[27]=64'h40e484b302075713;
        mem[28]=64'hf31ff0effff44503;
        mem[29]=64'hfe941ae3fff40413;
        mem[30]=64'h0381308303013403;
        mem[31]=64'h0401011302813483;
        mem[32]=64'h0300051300008067;
        mem[33]=64'hfe9ff06ff0dff0ef;
        mem[34]=64'h00113c23fe010113;
        mem[35]=64'h0005041300813823;
        mem[36]=64'h00a7ec6300100793;
        mem[37]=64'h0181308300040513;
        mem[38]=64'h0201011301013403;
        mem[39]=64'h0091342300008067;
        mem[40]=64'hfcdff0effff50513;
        mem[41]=64'hffe4051300050493;
        mem[42]=64'h00a48433fc1ff0ef;
        mem[43]=64'hfcdff06f00813483;
        mem[44]=64'h00113423ff010113;
        mem[45]=64'h0000051700813023;
        mem[46]=64'hec1ff0ef15c53503;
        mem[47]=64'h0f05051300000517;
        mem[48]=64'h00000417eb5ff0ef;
        mem[49]=64'h0000071714c40413;
        mem[50]=64'h0007268311c70713;
        mem[51]=64'h00d787bb00472783;
        mem[52]=64'h00d787bb00872683;
        mem[53]=64'h00d787bb00c72683;
        mem[54]=64'h00e787bb01072703;
        mem[55]=64'h0000051700f42023;
        mem[56]=64'he71ff0ef0b450513;
        mem[57]=64'hea1ff0ef00046503;
        mem[58]=64'h0985051300000517;
        mem[59]=64'h00000517e5dff0ef;
        mem[60]=64'he51ff0ef09c50513;
        mem[61]=64'hf25ff0ef00a00513;
        mem[62]=64'h00000517e7dff0ef;
        mem[63]=64'he39ff0ef07450513;
        mem[64]=64'h0c07879300000797;
        mem[65]=64'h010407130007b403;
        mem[66]=64'h0070079300e7b023;
        mem[67]=64'h0080079300f42023;
        mem[68]=64'h0090079300f42223;
        mem[69]=64'h0000051700f42423;
        mem[70]=64'he01ff0ef05c50513;
        mem[71]=64'h0044250300042783;
        mem[72]=64'h0084278300f5053b;
        mem[73]=64'h0205151300f5053b;
        mem[74]=64'he19ff0ef02055513;
        mem[75]=64'h0105051300000517;
        mem[76]=64'h0000006fdd5ff0ef;
        mem[77]=64'h0000000000000a0d;
        mem[78]=64'h000000003d6d7573;
        mem[79]=64'h3d29303128626966;
        mem[81]=64'h0000003d70616568;
        mem[82]=64'h2073676e69727473;
        mem[83]=64'h776f6e206b726f77;
        mem[84]=64'h0000000000000021;
        mem[85]=64'h000000140000000a;
        mem[86]=64'h000000280000001e;
        mem[87]=64'h0000000000000032;
        mem[88]=64'h00000000800002d8;
        mem[89]=64'h0000000080000290;
    end
    wire [14:0] a_idx = a_addr[17:3];
    wire [14:0] b_idx = b_addr[17:3];
    // ---- port A: instruction fetch (registered 32-bit read) ----
    always @(posedge clk) a_rdata <= a_addr[2] ? mem[a_idx][63:32] : mem[a_idx][31:0];
    // ---- port B: data, byte/half/word/double store + sized read ----
    wire [5:0] boff = {b_addr[2:0],3'b000};
    always @(posedge clk) if (b_we) begin
        case (b_funct3[1:0])
            2'b00: mem[b_idx][boff +:  8] <= b_wdata[7:0];
            2'b01: mem[b_idx][boff +: 16] <= b_wdata[15:0];
            2'b10: mem[b_idx][boff +: 32] <= b_wdata[31:0];
            2'b11: mem[b_idx]             <= b_wdata;
        endcase
    end
    reg [63:0] word_r; reg [5:0] boff_r; reg [2:0] f3_r;
    always @(posedge clk) begin word_r<=mem[b_idx]; boff_r<=boff; f3_r<=b_funct3; end
    wire [63:0] sub = word_r >> boff_r;
    always @(*) begin
        case (f3_r)
            3'b000: b_rdata = {{56{sub[7]}},  sub[7:0]};
            3'b001: b_rdata = {{48{sub[15]}}, sub[15:0]};
            3'b010: b_rdata = {{32{sub[31]}}, sub[31:0]};
            3'b011: b_rdata = word_r;
            3'b100: b_rdata = {56'b0, sub[7:0]};
            3'b101: b_rdata = {48'b0, sub[15:0]};
            3'b110: b_rdata = {32'b0, sub[31:0]};
            default: b_rdata = word_r;
        endcase
    end
endmodule
