#!/usr/bin/env python3
# Generate ah_dmem.v: a synchronous 64 KB data BRAM, optionally preloaded with
# a program's initialised data image. (c) 2026 Ali Hussein, GPL-3.0.
#   usage: ah_mkdmem.py out.v [data.bin base_word]
import sys, struct
WORDS=8192   # 8192 x 64-bit = 64 KB
preload=[]
if len(sys.argv)>2:
    data=open(sys.argv[2],'rb').read()
    base=int(sys.argv[3],0) if len(sys.argv)>3 else 0
    if len(data)%8: data+=b'\x00'*(8-len(data)%8)
    for i in range(0,len(data),8):
        w=struct.unpack('<Q',data[i:i+8])[0]
        if w: preload.append((base+i//8, w))
H='''// =============================================================================
//  AH-RISCV : synchronous data memory (64 KB BRAM). (c) 2026 Ali Hussein. GPL-3.0.
//  Hardware signature: "AHUSSEIN".  Generated by tools/ah_mkdmem.py.
//
//  Read and write are driven from the EX stage (address = ALU result), so the
//  registered read data is valid in the MEM stage -- load timing, forwarding,
//  and the load-use stall are identical to the old combinational memory.
//  Initialised .data/.rodata are baked into the array below; the rest is zero
//  (so .bss starts cleared and the stack/heap have room).
// ============================================================================='''
L=[H,'module ah_dmem (',
 '    input         clk,',
 '    input  [63:0] addr,      // EX-stage address (ALU result)',
 '    input  [63:0] wdata,     // store data (raw rs2)',
 '    input  [2:0]  funct3,',
 '    input         mem_read,',
 '    input         mem_write,',
 '    output reg [63:0] rdata  // valid next cycle (MEM stage), sign/zero-extended',
 ');',
 f'    reg [63:0] mem [0:{WORDS-1}];',
 '    integer i;',
 '    initial begin',
 f'        for (i=0;i<{WORDS};i=i+1) mem[i]=64\'d0;']
for idx,w in preload: L.append(f"        mem[{idx}]=64'h{w:016x};")
L+=['    end',
 f'    wire [12:0] widx = addr[15:3];',
 '    wire [5:0]  boff = {addr[2:0],3\'b000};',
 '    // byte/half/word/double store (assumes natural alignment)',
 '    always @(posedge clk) if (mem_write) begin',
 '        case (funct3[1:0])',
 '            2\'b00: mem[widx][boff +:  8] <= wdata[7:0];',
 '            2\'b01: mem[widx][boff +: 16] <= wdata[15:0];',
 '            2\'b10: mem[widx][boff +: 32] <= wdata[31:0];',
 '            2\'b11: mem[widx]             <= wdata;',
 '        endcase',
 '    end',
 '    // synchronous read: latch the word + alignment, extend combinationally',
 '    reg [63:0] word_r; reg [5:0] boff_r; reg [2:0] f3_r;',
 '    always @(posedge clk) begin',
 '        word_r <= mem[widx]; boff_r <= boff; f3_r <= funct3;',
 '    end',
 '    wire [63:0] sub = word_r >> boff_r;',
 '    always @(*) begin',
 '        case (f3_r)',
 '            3\'b000: rdata = {{56{sub[7]}},  sub[7:0]};',
 '            3\'b001: rdata = {{48{sub[15]}}, sub[15:0]};',
 '            3\'b010: rdata = {{32{sub[31]}}, sub[31:0]};',
 '            3\'b011: rdata = word_r;',
 '            3\'b100: rdata = {56\'b0, sub[7:0]};',
 '            3\'b101: rdata = {48\'b0, sub[15:0]};',
 '            3\'b110: rdata = {32\'b0, sub[31:0]};',
 '            default: rdata = word_r;',
 '        endcase',
 '    end',
 'endmodule','']
open(sys.argv[1],'w').write("\n".join(L))
print(f"{sys.argv[1]}: {WORDS} words (64 KB), {len(preload)} preloaded data words")
